export const mailSite='https://lossless-rewrite.vercel.app';
export function confirmationMessage(plan:string,unsubscribeUrl:string){
  if(!['plus','pro'].includes(plan))throw new Error('Invalid plan');
  const name=plan==='plus'?'Plus':'Pro';
  const safeUrl=unsubscribeUrl.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
  return {
    subject:`You're on the list for Lossless Rewrite ${name}`,
    textContent:`Hi,\n\nThanks for your interest in Lossless Rewrite ${name}. You're on the list.\n\nLess repetition. More room for your ideas. We're building ${name} to help you condense your writing and check what survived.\n\nWe'll email you with updates about ${name} and let you know when it's ready. No payment or subscription has started. You can keep using Free meanwhile.\n\nThanks for being here,\nFrancesco\nLossless Rewrite\n\nExplore the project: https://github.com/dttfrancesco/lossless-rewrite\n\nUnsubscribe from ${name} updates (no sign-in needed): ${unsubscribeUrl}`,
    htmlContent:`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>You're on the list</title></head><body style="margin:0;background:#f5f5f3;color:#202322;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">We'll let you know when ${name} is ready. Free is yours to keep using.</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#fff;border:1px solid #e4e5e1;border-radius:16px"><tr><td style="padding:32px 32px 24px"><table role="presentation" cellpadding="0" cellspacing="0"><tr><td><img src="${mailSite}/assets/logo.png" alt="" width="36" height="36" style="display:block;border:0"></td><td style="padding-left:12px;font:bold 25px Georgia,serif">lossless rewrite.</td></tr></table><p style="margin:36px 0 10px;font-size:13px;font-weight:bold;letter-spacing:1px;color:#536259">${name.toUpperCase()} · EARLY INTEREST</p><h1 style="margin:0 0 18px;font-size:34px;line-height:1.15;letter-spacing:-1px">You're on the list.</h1><p style="font-size:17px;line-height:1.6;margin:0">Hi,<br>Thanks for your interest in Lossless Rewrite ${name}. We'll keep you updated and let you know when it's ready.</p></td></tr><tr><td style="padding:0 24px"><img src="${mailSite}/assets/less-words-v2.png" alt="Cut words, not ideas. Example: The trial lasted six weeks, but had no control group. Shortened: Six-week trial; no control group." width="552" style="display:block;width:100%;max-width:552px;height:auto;border:0;border-radius:10px"></td></tr><tr><td style="padding:24px 32px 32px"><p style="font-size:16px;line-height:1.65;margin:0 0 20px">No payment or subscription has started. You can keep using Free while we work on ${name}.</p><a href="https://github.com/dttfrancesco/lossless-rewrite" style="display:inline-block;padding:13px 19px;border-radius:7px;background:#202322;color:#fff;text-decoration:none;font-size:15px;font-weight:bold">Explore Lossless Rewrite ↗</a><p style="font-size:16px;line-height:1.65;margin:28px 0 0">Thanks for being here,<br><strong>Francesco</strong><br><span style="color:#66716a">Creator of Lossless Rewrite</span></p></td></tr></table><p style="max-width:540px;margin:20px auto 0;color:#647067;font-size:12px;line-height:1.7">You asked for updates about Lossless Rewrite ${name}.<br><a href="${safeUrl}" style="color:#3e4c43;text-decoration:underline">Unsubscribe from ${name} updates</a> · No sign-in needed.</p></td></tr></table></body></html>`,
  };
}
